Repository ucsb-cs156-m23/proj-gauchoride-m23-9am-2, pull requests merged in 2023-08, with the labels that each got.

#18 Adds a string cellPhone
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
Labels: 5

#25 Changes following link by Prof
  src/main/resources/application.properties
Labels: 5

#38 form component, tests, and mutations for Driver Shift Table
  frontend/src/fixtures/shiftFixtures.js
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/stories/components/Shift/ShiftForm.stories.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
Labels: 10

#60 Made changes to Stryker Work flow
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
Labels: 5

#48 Andrew rider application repo
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/RiderApplicationRepository.java
Labels: 5, MergeCandidate-Waiting on CI

#62 Andrew rider application fixture
  frontend/src/fixtures/riderApplicationFixtures.js
Labels: 5, MergeCandidate-Waiting on CI

#68 Mohamed package changes
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
Labels: FIXME-team CR, PRIORITY FOR MOHAMED's PRs

#70 Driver Page
  frontend/src/App.js
  frontend/src/fixtures/drivershiftsFixtures.js
  frontend/src/main/components/Driver/DriverShiftsTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DriverPage.js
  frontend/src/tests/components/Driver/DriverShiftsTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/DriverPage.test.js
Labels: 10, MergeCandidate-Waiting on CI
